"""reaarange columns waste_listings table

Revision ID: ae076d2f0298
Revises: 63bc4af0ee14
Create Date: 2025-03-27 20:21:37.816028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae076d2f0298'
down_revision = '63bc4af0ee14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_listing', schema=None) as batch_op:
        batch_op.drop_column('required_by')
        batch_op.drop_column('responses')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responses', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('required_by', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
